export const Pages = {
    index: 'index',
    dashboard: 'dashboard',
    home: 'home',
    forget: 'forget',
    recommend: 'recommend',
    discover: 'discover',
    login: 'login',

    profile: 'profile',
    member: 'member',
    memberInfo: 'memberInfo',
    profileInfo: 'profileInfo',
    profileSetUsername: 'profileSetUsername',
    profileSetNickname: 'profileSetNickname',
    profileSetSignature: 'profileSetSignature',
    profileSetPhone: 'profileSetPhone',
    profileSetPassword: 'profileSetPassword',

    creativeCenter: 'creativeCenter',
    myIndex: 'myIndex',
    myAlbum: 'myAlbum',
    albumDetail: 'albumDetail',
    albumVideoList: 'albumVideoList',
    albumCommentList: 'albumCommentList',
    albumShowList: "albumShowList",
    albumSimilarRecommendList: 'albumSimilarRecommendList',

    albumStatistic: 'albumStatistic',
    basicData: 'basicData',
    audienceAnalysis: 'audienceAnalysis',

    albumCreate: 'albumCreate',
    albumSetTitle: 'albumSetTitle',
    albumSetRemark: 'albumSetRemark',
    albumSetAttributes: 'albumSetAttributes',

    videoUpload: 'videoUpload',
    videoDescription: 'videoDescription',
    videoSetTitle: 'videoSetTitle',
}