export const Pages = {
    index: 'index',
    dashboard: 'dashboard',
    home: 'home',
    forget: 'forget',
    recommend: 'recommend',
    discover: 'discover',
    login: 'login',

    profile: 'profile',
    member: 'member',
    memberInfo: 'memberInfo',
    profileInfo: 'profileInfo',
    profileSetUsername: 'profileSetUsername',
    profileSetNickname: 'profileSetNickname',
    profileSetSignature: 'profileSetSignature',
    profileSetPhone: 'profileSetPhone',
    profileSetPassword: 'profileSetPassword',
    planCategory: 'planCategory',
    vipPlatinumDetail: 'vipPlatinumDetail',
    courseDetail: 'courseDetail',
    familyDetail: 'familyDetail',
    kidsDetail: 'kidsDetail',
    sVipDetail: 'sVipDetail',
    vipDetail: 'vipDetail',

    creativeCenter: 'creativeCenter',
    myIndex: 'myIndex',
    myAlbum: 'myAlbum',
    albumCreativeDetail: 'albumCreativeDetail',
    albumCreativeVideoList: 'albumCreativeVideoList',
    albumCreativeCommentList: 'albumCreativeCommentList',
    albumCreativeShowList: "albumCreativeShowList",
    albumDetail: 'albumDetail',
    albumVideoList: 'albumVideoList',
    albumCommentList: 'albumCommentList',
    albumShowList: "albumShowList",
    albumSimilarRecommendList: 'albumSimilarRecommendList',

    albumVideoListForRecall: 'albumVideoListForRecall',
    albumCommentListForRecall: 'albumCommentListForRecall',
    albumShowListForRecall: "albumShowListForRecall",
    albumSimilarRecommendListForRecall: 'albumSimilarRecommendListForRecall',

    albumStatistic: 'albumStatistic',
    basicData: 'basicData',
    audienceAnalysis: 'audienceAnalysis',

    albumCreate: 'albumCreate',
    albumSetTitle: 'albumSetTitle',
    albumSetRemark: 'albumSetRemark',
    albumSetAttributes: 'albumSetAttributes',

    videoUpload: 'videoUpload',
    videoDescription: 'videoDescription',
    videoSetTitle: 'videoSetTitle',

    soundDetail: 'soundDetail',
    mediaComments: 'mediaComments',

    vipOrderConfirm: 'vipOrderConfirm',
    vipProtocol: 'vipProtocol',
    paymentResult: 'paymentResult',
    orderCenter:'orderCenter',
    allOrders:'allOrders',
    pendingPaymentOrders:'pendingPaymentOrders',
    commentOrders:'commentOrders',
    orderDetail:'orderDetail',
    orderCommentWrite:'orderCommentWrite',
}